/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime';
import type { DatasetIssue } from '../models';
import { DatasetIssueFromJSON, DatasetIssueToJSON } from '../models';

/**
 *
 */
export class IssuesApi extends runtime.BaseAPI {
    /**
     * Get all data issues.
     * Get All
     */
    async getAllRaw(
        initOverrides?: RequestInit | runtime.InitOverrideFunction
    ): Promise<runtime.ApiResponse<Array<DatasetIssue>>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request(
            {
                path: `/api/issues/`,
                method: 'GET',
                headers: headerParameters,
                query: queryParameters,
            },
            initOverrides
        );

        return new runtime.JSONApiResponse(response, (jsonValue) =>
            jsonValue.map(DatasetIssueFromJSON)
        );
    }

    /**
     * Get all data issues.
     * Get All
     */
    async getAll(
        initOverrides?: RequestInit | runtime.InitOverrideFunction
    ): Promise<Array<DatasetIssue>> {
        const response = await this.getAllRaw(initOverrides);
        return await response.value();
    }
}
