"""AUTO GENERATED BY generate_ui_test_elements.py"""


class DataTestTags:  # pylint: disable=too-few-public-methods
    """list of all tags found in src/*.ts*"""

    DATAGRID = "datagrid"
    DATAGRID_ADD_COLUMN_BUTTON = "datagrid-add-column-button"
    DATAGRID_ALL_COUNT = "datagrid-all-count"
    DATAGRID_ALL_TAB_BUTTON = "datagrid-all-tab-button"
    DATAGRID_FILTERED_COUNT = "datagrid-filtered-count"
    DATAGRID_FILTERED_TAB_BUTTON = "datagrid-filtered-tab-button"
    DATAGRID_SELECTED_COUNT = "datagrid-selected-count"
    DATAGRID_SELECTED_TAB_BUTTON = "datagrid-selected-tab-button"
    DATAGRID_SETTINGS_DROPDOWN = "datagrid-settings-dropdown"
    GLOBAL_LOADING_INDICATOR = "global-loading-indicator"
    HELP_BUTTON = "help-button"
    MESHVIEW_SETTINGS_DROPDOWN = "meshview-settings-dropdown"
    SEQUENCEVIEW_SETTINGS_DROPDOWN = "sequenceview-settings-dropdown"
    SIMILARITYMAP = "similaritymap"
    SIMILARITYMAP_SETTINGS_DROPDOWN = "similaritymap-settings-dropdown"
