"""Tests for ordering the table columns by their relevance"""

import time
from typing import Any

from selenium.webdriver.remote.webdriver import WebDriver

from .basic_actions import ctrl_click, open_app
from .helpers import (
    get_table_cell,
    get_visible_column_names,
    screenshot_exception,
    wait_for_css_element,
    wait_for_tagged_element,
)


def test_columns_are_ordered_by_relevance(
    webdriver: WebDriver,
    frontend_base_url: str,
    loaded_selection_example_dataset: Any,
    skip_tour: None,
) -> None:
    """
    test the columns in which the selected rows differ most from all rows come first
    when the columns are ordered by relevance
    """
    from ._autogenerated_ui_elements import DataTestTags

    with screenshot_exception(webdriver):
        open_app(webdriver, frontend_base_url)
        default_order = get_visible_column_names(webdriver)

        wait_for_tagged_element(
            webdriver, DataTestTags.DATAGRID_SETTINGS_DROPDOWN
        ).click()
        wait_for_css_element(webdriver, "input[type='checkbox']").click()

        # the rows with the highest numbers (and high scores), which stand out in both
        for row in (1, 13, 14, 15):
            ctrl_click(webdriver, get_table_cell(webdriver, row))
        time.sleep(2)

        assert get_visible_column_names(webdriver) != default_order
        assert set(get_visible_column_names(webdriver)[:2]) == {"number", "score"}
