"""Tests for selecting rows in the table by mouse"""

import time
from typing import Any

from selenium.webdriver import ActionChains
from selenium.webdriver.common.actions.wheel_input import ScrollOrigin
from selenium.webdriver.remote.webdriver import WebDriver

from .basic_actions import open_app
from .example_tables import selection_example_ids
from .helpers import (
    get_column_index,
    get_selected_count,
    get_tab,
    get_table_cell,
    screenshot_exception,
    wait_for_css_element,
    wait_for_tagged_element,
)


def test_press_and_release_in_different_cells_selects_pressed_row(
    webdriver: WebDriver,
    frontend_base_url: str,
    loaded_selection_example_dataset: Any,
    skip_tour: None,
) -> None:
    """
    test a click that ends in the cell below the one it began in selects the row it began in
    (and not the first row)
    """
    with screenshot_exception(webdriver):
        open_app(webdriver, frontend_base_url)
        cell = get_table_cell(webdriver, 4)
        height = cell.size["height"]

        # press 2 px above the lower border of the row, release 2 px below it:
        # a movement too short to be a drag
        ActionChains(webdriver).move_to_element_with_offset(
            cell, 5, height // 2 - 2
        ).click_and_hold().move_by_offset(0, 4).release().perform()
        time.sleep(0.5)

        assert get_selected_count(webdriver) == 1
        get_tab(webdriver, "Selected").click()
        id_column = get_column_index(webdriver, "id")
        assert (
            get_table_cell(webdriver, 0, id_column).text == selection_example_ids(40)[4]
        )


def test_press_held_for_half_a_second_selects_row(
    webdriver: WebDriver,
    frontend_base_url: str,
    loaded_selection_example_dataset: Any,
    skip_tour: None,
) -> None:
    """
    test a slow click (a press held for a while) selects the row and does not start a drag
    """
    with screenshot_exception(webdriver):
        open_app(webdriver, frontend_base_url)
        cell = get_table_cell(webdriver, 2)

        ActionChains(webdriver).move_to_element(cell).click_and_hold().pause(
            0.5
        ).release().perform()
        time.sleep(0.5)

        assert get_selected_count(webdriver) == 1


def test_click_with_small_movement_selects_row(
    webdriver: WebDriver,
    frontend_base_url: str,
    loaded_selection_example_dataset: Any,
    skip_tour: None,
) -> None:
    """
    test a click whose pointer moves a few pixels selects the row and does not start a drag
    """
    with screenshot_exception(webdriver):
        open_app(webdriver, frontend_base_url)
        cell = get_table_cell(webdriver, 3)

        ActionChains(webdriver).move_to_element(cell).click_and_hold().move_by_offset(
            8, 0
        ).release().perform()
        time.sleep(0.5)

        assert get_selected_count(webdriver) == 1


def test_cell_can_be_dragged_to_filter_bar(
    webdriver: WebDriver,
    frontend_base_url: str,
    loaded_selection_example_dataset: Any,
    skip_tour: None,
) -> None:
    """
    test dragging a cell to the filter bar still adds a filter for its value,
    without selecting the row
    """
    from ._autogenerated_ui_elements import DataTestTags

    with screenshot_exception(webdriver):
        open_app(webdriver, frontend_base_url)
        cell = get_table_cell(webdriver, 5, get_column_index(webdriver, "id"))
        filter_bar = wait_for_css_element(webdriver, "[data-tour='filterBar']")

        ActionChains(webdriver).move_to_element(cell).click_and_hold().move_by_offset(
            0, -30
        ).move_to_element(filter_bar).release().perform()
        time.sleep(0.5)

        filtered_count = wait_for_tagged_element(
            webdriver, DataTestTags.DATAGRID_FILTERED_COUNT
        )
        assert int(filtered_count.text) == 1
        assert get_selected_count(webdriver) == 0


def test_cell_can_be_dragged_after_a_scroll(
    webdriver: WebDriver,
    frontend_base_url: str,
    loaded_selection_example_dataset: Any,
    skip_tour: None,
) -> None:
    """
    test a cell that came into view by a scroll can be dragged to the filter bar, also
    when the pointer has not moved since the scroll
    """
    from ._autogenerated_ui_elements import DataTestTags

    with screenshot_exception(webdriver):
        open_app(webdriver, frontend_base_url)
        id_column = get_column_index(webdriver, "id")
        cell = get_table_cell(webdriver, 5, id_column)
        filter_bar = wait_for_css_element(webdriver, "[data-tour='filterBar']")

        # the pointer is moved to the middle of the cell and not moved again
        x = cell.location["x"] + cell.size["width"] / 2
        y = cell.location["y"] + cell.size["height"] / 2
        ActionChains(webdriver).move_to_element(cell).scroll_from_origin(
            ScrollOrigin.from_element(cell), 0, 150
        ).pause(1).perform()
        # the table scrolled: under the pointer is the cell of another row
        under_pointer = webdriver.execute_script(
            "return document.elementFromPoint(arguments[0], arguments[1])"
            ".closest('div[data-rowindex]').textContent",
            x,
            y,
        )
        assert under_pointer not in ("", selection_example_ids(40)[5])

        ActionChains(webdriver).click_and_hold().move_by_offset(0, -30).move_to_element(
            filter_bar
        ).release().perform()
        time.sleep(0.5)

        filtered_count = wait_for_tagged_element(
            webdriver, DataTestTags.DATAGRID_FILTERED_COUNT
        )
        assert int(filtered_count.text) == 1
        assert get_selected_count(webdriver) == 0
