"""Tests for the video lens"""

import time
from typing import Any

from selenium.webdriver.remote.webdriver import WebDriver

from .helpers import (
    screenshot_exception,
    wait_for_css_element,
    wait_for_tagged_element,
)


def test_video_lens_shows_video_player(
    webdriver: WebDriver,
    frontend_base_url: str,
    loaded_selection_example_dataset: Any,
    skip_tour: None,
) -> None:
    """
    test the inspector shows a video player for a row with a video
    """
    from ._autogenerated_ui_elements import DataTestTags

    with screenshot_exception(webdriver):
        webdriver.get(frontend_base_url)
        wait_for_tagged_element(webdriver, DataTestTags.HELP_BUTTON)
        time.sleep(1)

        wait_for_css_element(webdriver, "div[data-rowindex='0']").click()

        wait_for_css_element(webdriver, "video")
        assert "Error Creating Video Player" not in webdriver.page_source
