"""Tests for the example table the selection tests use"""

from typing import Any

from selenium.webdriver.remote.webdriver import WebDriver

from .basic_actions import ctrl_click, open_app, shift_click
from .example_tables import selection_example_ids
from .helpers import (
    get_column_index,
    get_selected_count,
    get_tab,
    get_table_cell,
    screenshot_exception,
    wait_for_tagged_element,
)


def test_example_table_is_shown(
    webdriver: WebDriver,
    frontend_base_url: str,
    loaded_selection_example_dataset: Any,
    skip_tour: None,
) -> None:
    """
    test the table of made-up data is loaded: all rows shown, none selected
    """
    from ._autogenerated_ui_elements import DataTestTags

    with screenshot_exception(webdriver):
        open_app(webdriver, frontend_base_url)

        all_count = wait_for_tagged_element(webdriver, DataTestTags.DATAGRID_ALL_COUNT)
        assert int(all_count.text) == 40
        assert get_selected_count(webdriver) == 0
        id_column = get_column_index(webdriver, "id")
        assert get_table_cell(webdriver, 0, id_column).text == "item-0000"


def test_click_with_modifier_keys_selects_several_rows(
    webdriver: WebDriver,
    frontend_base_url: str,
    loaded_selection_example_dataset: Any,
    skip_tour: None,
) -> None:
    """
    test control click adds single rows to the selection, shift click adds a range of rows
    """
    with screenshot_exception(webdriver):
        open_app(webdriver, frontend_base_url)

        get_table_cell(webdriver, 2).click()
        assert get_selected_count(webdriver) == 1
        ctrl_click(webdriver, get_table_cell(webdriver, 5))
        ctrl_click(webdriver, get_table_cell(webdriver, 9))
        assert get_selected_count(webdriver) == 3
        # a click with the control key held deselects a selected row
        ctrl_click(webdriver, get_table_cell(webdriver, 5))
        assert get_selected_count(webdriver) == 2
        # shift click adds the rows between the last selected row and the clicked row
        shift_click(webdriver, get_table_cell(webdriver, 14))
        assert get_selected_count(webdriver) == 2 + 5

        # the ids that are selected: the selected rows are listed in the order they were selected
        get_tab(webdriver, "Selected").click()
        ids = selection_example_ids(40)
        id_column = get_column_index(webdriver, "id")
        shown = [get_table_cell(webdriver, row, id_column).text for row in range(7)]
        assert shown == [ids[i] for i in (2, 9, 10, 11, 12, 13, 14)]
