"""Tests for basic interactions"""
import time
from typing import Any
from selenium.webdriver.common.by import By
from selenium.webdriver.remote.webdriver import WebDriver

from ui_tests.helpers import (
    wait_for_tagged_element,
    get_tab,
    screenshot_exception,
)


def test_tabs_available(
    webdriver: WebDriver,
    tallymarks_dataset: Any,  # pylint:disable=unused-argument
    frontend_base_url: str,
    skip_tour: None,  # pylint:disable=unused-argument
) -> None:
    """
    test to click tabs
    """

    from ui_tests._autogenerated_ui_elements import DataTestTags  # pylint: disable-all

    with screenshot_exception(webdriver):
        webdriver.get(frontend_base_url)
        driver = webdriver

        wait_for_tagged_element(webdriver, DataTestTags.HELP_BUTTON)

        time.sleep(1.0)

        wait_for_tagged_element(webdriver, DataTestTags.DATAGRID_ALL_TAB_BUTTON)
        num = int(
            wait_for_tagged_element(webdriver, DataTestTags.DATAGRID_ALL_COUNT).text
        )
        assert num > 10
        tab = wait_for_tagged_element(webdriver, DataTestTags.DATAGRID_ALL_TAB_BUTTON)
        tab.click()

        wait_for_tagged_element(webdriver, DataTestTags.DATAGRID_FILTERED_TAB_BUTTON)
        num = int(
            wait_for_tagged_element(
                webdriver, DataTestTags.DATAGRID_FILTERED_COUNT
            ).text
        )
        assert num > 10
        tab = wait_for_tagged_element(
            webdriver, DataTestTags.DATAGRID_FILTERED_TAB_BUTTON
        )
        tab.click()

        wait_for_tagged_element(webdriver, DataTestTags.DATAGRID_SELECTED_TAB_BUTTON)
        num = int(
            wait_for_tagged_element(
                webdriver, DataTestTags.DATAGRID_SELECTED_COUNT
            ).text
        )
        assert num == 0
        tab = wait_for_tagged_element(
            webdriver, DataTestTags.DATAGRID_SELECTED_TAB_BUTTON
        )

        tab.click()

        tab = get_tab(driver, "Scatter Plot")
        tab.click()

        tab = get_tab(driver, "Histogram")
        tab.click()

        tab = get_tab(driver, "Similarity Map")
        tab.click()

        tab = get_tab(driver, "Inspector")
        tab.click()


def test_tagged_elements_available(
    webdriver: WebDriver,
    tallymarks_dataset: Any,  # pylint:disable=unused-argument
    frontend_base_url: str,
    skip_tour: None,  # pylint:disable=unused-argument
) -> None:
    """
    test that elements with data-test-tag are available
    """
    from ui_tests._autogenerated_ui_elements import DataTestTags  # pylint: disable-all

    with screenshot_exception(webdriver):
        webdriver.get(frontend_base_url)

        driver = webdriver

        wait_for_tagged_element(webdriver, DataTestTags.HELP_BUTTON)

        for tag in [
            tag for name, tag in vars(DataTestTags).items() if not name.startswith("_")
        ]:
            if not tag in [
                DataTestTags.GLOBAL_LOADING_INDICATOR,
                DataTestTags.MESHVIEW_SETTINGS_DROPDOWN,
                DataTestTags.SEQUENCEVIEW_SETTINGS_DROPDOWN,
            ]:
                element = wait_for_tagged_element(webdriver, tag, 1)
                if "dropdown" in tag or "button" in tag:
                    element.click()
                driver.find_element(by=By.XPATH, value="//body").click()
