/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { DataIssue } from './DataIssue';
import {
    DataIssueFromJSON,
    DataIssueFromJSONTyped,
    DataIssueToJSON,
} from './DataIssue';

/**
 * The current analysis status with all issues
 * @export
 * @interface AnalysisInfo
 */
export interface AnalysisInfo {
    /**
     *
     * @type {boolean}
     * @memberof AnalysisInfo
     */
    running: boolean;
    /**
     *
     * @type {Array<DataIssue>}
     * @memberof AnalysisInfo
     */
    issues: Array<DataIssue>;
}

/**
 * Check if a given object implements the AnalysisInfo interface.
 */
export function instanceOfAnalysisInfo(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && 'running' in value;
    isInstance = isInstance && 'issues' in value;

    return isInstance;
}

export function AnalysisInfoFromJSON(json: any): AnalysisInfo {
    return AnalysisInfoFromJSONTyped(json, false);
}

export function AnalysisInfoFromJSONTyped(
    json: any,
    ignoreDiscriminator: boolean
): AnalysisInfo {
    if (json === undefined || json === null) {
        return json;
    }
    return {
        running: json['running'],
        issues: (json['issues'] as Array<any>).map(DataIssueFromJSON),
    };
}

export function AnalysisInfoToJSON(value?: AnalysisInfo | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        running: value.running,
        issues: (value.issues as Array<any>).map(DataIssueToJSON),
    };
}
