/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 *
 * @export
 * @interface ArrayDType
 */
export interface ArrayDType {
    /**
     *
     * @type {string}
     * @memberof ArrayDType
     */
    name?: ArrayDTypeNameEnum;
    /**
     *
     * @type {Array<number>}
     * @memberof ArrayDType
     */
    shape?: Array<number>;
}

/**
 * @export
 */
export const ArrayDTypeNameEnum = {
    Array: 'array',
} as const;
export type ArrayDTypeNameEnum =
    typeof ArrayDTypeNameEnum[keyof typeof ArrayDTypeNameEnum];

/**
 * Check if a given object implements the ArrayDType interface.
 */
export function instanceOfArrayDType(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function ArrayDTypeFromJSON(json: any): ArrayDType {
    return ArrayDTypeFromJSONTyped(json, false);
}

export function ArrayDTypeFromJSONTyped(
    json: any,
    ignoreDiscriminator: boolean
): ArrayDType {
    if (json === undefined || json === null) {
        return json;
    }
    return {
        name: !exists(json, 'name') ? undefined : json['name'],
        shape: !exists(json, 'shape') ? undefined : json['shape'],
    };
}

export function ArrayDTypeToJSON(value?: ArrayDType | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        name: value.name,
        shape: value.shape,
    };
}
