/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 *
 * @export
 * @interface BaseDType
 */
export interface BaseDType {
    /**
     *
     * @type {string}
     * @memberof BaseDType
     */
    name: string;
}

/**
 * Check if a given object implements the BaseDType interface.
 */
export function instanceOfBaseDType(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && 'name' in value;

    return isInstance;
}

export function BaseDTypeFromJSON(json: any): BaseDType {
    return BaseDTypeFromJSONTyped(json, false);
}

export function BaseDTypeFromJSONTyped(
    json: any,
    ignoreDiscriminator: boolean
): BaseDType {
    if (json === undefined || json === null) {
        return json;
    }
    return {
        name: json['name'],
    };
}

export function BaseDTypeToJSON(value?: BaseDType | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        name: value.name,
    };
}
