/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 *
 * @export
 * @interface BoundingBox
 */
export interface BoundingBox {
    /**
     *
     * @type {string}
     * @memberof BoundingBox
     */
    name?: BoundingBoxNameEnum;
}

/**
 * @export
 */
export const BoundingBoxNameEnum = {
    BoundingBox: 'BoundingBox',
} as const;
export type BoundingBoxNameEnum =
    typeof BoundingBoxNameEnum[keyof typeof BoundingBoxNameEnum];

/**
 * Check if a given object implements the BoundingBox interface.
 */
export function instanceOfBoundingBox(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function BoundingBoxFromJSON(json: any): BoundingBox {
    return BoundingBoxFromJSONTyped(json, false);
}

export function BoundingBoxFromJSONTyped(
    json: any,
    ignoreDiscriminator: boolean
): BoundingBox {
    if (json === undefined || json === null) {
        return json;
    }
    return {
        name: !exists(json, 'name') ? undefined : json['name'],
    };
}

export function BoundingBoxToJSON(value?: BoundingBox | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        name: value.name,
    };
}
