/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { Severity } from './Severity';
import { SeverityFromJSON, SeverityFromJSONTyped, SeverityToJSON } from './Severity';

/**
 * A Problem affecting multiple rows of the dataset
 * @export
 * @interface DatasetIssue
 */
export interface DatasetIssue {
    /**
     *
     * @type {Severity}
     * @memberof DatasetIssue
     */
    severity: Severity;
    /**
     *
     * @type {string}
     * @memberof DatasetIssue
     */
    description: string;
    /**
     *
     * @type {Array<number>}
     * @memberof DatasetIssue
     */
    rows: Array<number>;
}

/**
 * Check if a given object implements the DatasetIssue interface.
 */
export function instanceOfDatasetIssue(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && 'severity' in value;
    isInstance = isInstance && 'description' in value;
    isInstance = isInstance && 'rows' in value;

    return isInstance;
}

export function DatasetIssueFromJSON(json: any): DatasetIssue {
    return DatasetIssueFromJSONTyped(json, false);
}

export function DatasetIssueFromJSONTyped(
    json: any,
    ignoreDiscriminator: boolean
): DatasetIssue {
    if (json === undefined || json === null) {
        return json;
    }
    return {
        severity: SeverityFromJSON(json['severity']),
        description: json['description'],
        rows: json['rows'],
    };
}

export function DatasetIssueToJSON(value?: DatasetIssue | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        severity: SeverityToJSON(value.severity),
        description: value.description,
        rows: value.rows,
    };
}
