/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { Type } from './Type';
import { TypeFromJSON, TypeFromJSONTyped, TypeToJSON } from './Type';

/**
 *
 * @export
 * @interface DatasetProblem
 */
export interface DatasetProblem {
    /**
     *
     * @type {Type}
     * @memberof DatasetProblem
     */
    type: Type;
    /**
     *
     * @type {string}
     * @memberof DatasetProblem
     */
    description: string;
    /**
     *
     * @type {Array<number>}
     * @memberof DatasetProblem
     */
    rows: Array<number>;
}

/**
 * Check if a given object implements the DatasetProblem interface.
 */
export function instanceOfDatasetProblem(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && 'type' in value;
    isInstance = isInstance && 'description' in value;
    isInstance = isInstance && 'rows' in value;

    return isInstance;
}

export function DatasetProblemFromJSON(json: any): DatasetProblem {
    return DatasetProblemFromJSONTyped(json, false);
}

export function DatasetProblemFromJSONTyped(
    json: any,
    ignoreDiscriminator: boolean
): DatasetProblem {
    if (json === undefined || json === null) {
        return json;
    }
    return {
        type: TypeFromJSON(json['type']),
        description: json['description'],
        rows: json['rows'],
    };
}

export function DatasetProblemToJSON(value?: DatasetProblem | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        type: TypeToJSON(value.type),
        description: value.description,
        rows: value.rows,
    };
}
