/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 *
 * @export
 * @interface EmbeddingDType
 */
export interface EmbeddingDType {
    /**
     *
     * @type {string}
     * @memberof EmbeddingDType
     */
    name?: EmbeddingDTypeNameEnum;
    /**
     *
     * @type {number}
     * @memberof EmbeddingDType
     */
    length?: number;
}

/**
 * @export
 */
export const EmbeddingDTypeNameEnum = {
    Embedding: 'Embedding',
} as const;
export type EmbeddingDTypeNameEnum =
    typeof EmbeddingDTypeNameEnum[keyof typeof EmbeddingDTypeNameEnum];

/**
 * Check if a given object implements the EmbeddingDType interface.
 */
export function instanceOfEmbeddingDType(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function EmbeddingDTypeFromJSON(json: any): EmbeddingDType {
    return EmbeddingDTypeFromJSONTyped(json, false);
}

export function EmbeddingDTypeFromJSONTyped(
    json: any,
    ignoreDiscriminator: boolean
): EmbeddingDType {
    if (json === undefined || json === null) {
        return json;
    }
    return {
        name: !exists(json, 'name') ? undefined : json['name'],
        length: !exists(json, 'length') ? undefined : json['length'],
    };
}

export function EmbeddingDTypeToJSON(value?: EmbeddingDType | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        name: value.name,
        length: value.length,
    };
}
