/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 *
 * @export
 * @interface ResponseGetValue
 */
export interface ResponseGetValue {}

/**
 * Check if a given object implements the ResponseGetValue interface.
 */
export function instanceOfResponseGetValue(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function ResponseGetValueFromJSON(json: any): ResponseGetValue {
    return ResponseGetValueFromJSONTyped(json, false);
}

export function ResponseGetValueFromJSONTyped(
    json: any,
    ignoreDiscriminator: boolean
): ResponseGetValue {
    return json;
}

export function ResponseGetValueToJSON(value?: ResponseGetValue | null): any {
    return value;
}
