/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 *
 * @export
 * @interface ResponseGet
 */
export interface ResponseGet {}

/**
 * Check if a given object implements the ResponseGet interface.
 */
export function instanceOfResponseGet(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function ResponseGetFromJSON(json: any): ResponseGet {
    return ResponseGetFromJSONTyped(json, false);
}

export function ResponseGetFromJSONTyped(
    json: any,
    ignoreDiscriminator: boolean
): ResponseGet {
    return json;
}

export function ResponseGetToJSON(value?: ResponseGet | null): any {
    return value;
}
