/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 *
 * @export
 * @interface Severity
 */
export interface Severity {}

/**
 * Check if a given object implements the Severity interface.
 */
export function instanceOfSeverity(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function SeverityFromJSON(json: any): Severity {
    return SeverityFromJSONTyped(json, false);
}

export function SeverityFromJSONTyped(
    json: any,
    ignoreDiscriminator: boolean
): Severity {
    return json;
}

export function SeverityToJSON(value?: Severity | null): any {
    return value;
}
